WITH PYTHON AS (SELECT SUM(CODE) AS PYTHON
FROM SKILLCODES
WHERE NAME = 'Python'), 

CHASHTAG AS (SELECT SUM(CODE) AS CHASHTAG
FROM SKILLCODES
WHERE NAME = 'C#'), 

FRONTEND AS (SELECT SUM(CODE) AS FRONTEND
FROM SKILLCODES
WHERE CATEGORY = 'Front End')

SELECT CASE
    WHEN SKILL_CODE & (SELECT FRONTEND FROM FRONTEND) != 0 
        AND SKILL_CODE & (SELECT PYTHON FROM PYTHON) != 0 THEN 'A'
    WHEN SKILL_CODE & (SELECT CHASHTAG FROM CHASHTAG) != 0 THEN 'B'
    WHEN SKILL_CODE & (SELECT FRONTEND FROM FRONTEND) != 0 AND 
    SKILL_CODE & (SELECT PYTHON FROM PYTHON) = 0 THEN 'C'
    END AS GRADE, 
    ID, EMAIL
FROM DEVELOPERS
HAVING GRADE IS NOT NULL
ORDER BY GRADE ASC, ID ASC

-- Group by 활용
SELECT 
    CASE 
        -- 1. 프론트엔드 스킬이 하나라도 있고(SUM > 0) AND 파이썬이 있는 경우, COUNT는 Python이 존재하지 않아도 전부 셈
        WHEN SUM(CATEGORY = 'Front End') > 0 AND SUM(NAME = 'Python') > 0 THEN 'A'
        -- 2. 위 조건은 아니지만 C#이 있는 경우
        WHEN SUM(NAME = 'C#') > 0 THEN 'B'
        -- 3. 위 조건은 아니지만 프론트엔드 스킬이 하나라도 있는 경우
        WHEN SUM(CATEGORY = 'Front End') > 0 THEN 'C'
    END AS GRADE,
    ID, 
    EMAIL
FROM (
    SELECT D.ID, D.EMAIL, S.NAME, S.CATEGORY
    FROM DEVELOPERS D
    JOIN SKILLCODES S ON (D.SKILL_CODE & S.CODE) = S.CODE -- 여러개의 기술을 가졌으면, 그 기술을 전부 나열하게 됨
) AS JOINED_TABLE
GROUP BY ID, EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID;