WITH MAY_ORDER AS (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
FROM FOOD_ORDER
WHERE PRODUCE_DATE LIKE '2022-05-%'
GROUP BY PRODUCT_ID)

SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, PRICE * AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT FP JOIN MAY_ORDER MO ON FP.PRODUCT_ID = MO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID ASC