-- Table: FISH_INFO
-- Att: ID, FISH_TYPE, LENGTH, TIME
-- Table: FISH_NAME_INFO
-- Att: FISH_TYPE, FISH_NAME

-- 서브쿼리 활용
SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE (FI.FISH_TYPE, LENGTH) IN (SELECT FISH_TYPE, MAX(LENGTH)
                                FROM FISH_INFO
                                GROUP BY FISH_TYPE)
ORDER BY FI.ID ASC;

-- RANK OVER 활용
SELECT RF.ID, FNI.FISH_NAME, RF.LENGTH
FROM (
    -- 물고기 종류별로 구분, 길이를 기준으로 내림차순해서 설정
    SELECT *, RANK() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RK
    FROM FISH_INFO
) AS RF 
JOIN FISH_NAME_INFO FNI ON RF.FISH_TYPE = FNI.FISH_TYPE
WHERE RF.RK = 1
ORDER BY RF.ID ASC;