WITH SCORE_AVG AS (SELECT EMP_NO, AVG(SCORE) AS SCORE
FROM HR_GRADE
GROUP BY EMP_NO)

SELECT HE.EMP_NO, HE.EMP_NAME, 
    CASE 
        WHEN SA.SCORE >= 96 THEN 'S'
        WHEN SA.SCORE >= 90 THEN 'A'
        WHEN SA.SCORE >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN SA.SCORE >= 96 THEN HE.SAL * 0.2
        WHEN SA.SCORE >= 90 THEN HE.SAL * 0.15
        WHEN SA.SCORE >= 80 THEN HE.SAL * 0.1
        ELSE 0
    END AS BONUS
FROM (HR_EMPLOYEES HE 
LEFT JOIN SCORE_AVG SA 
ON HE.EMP_NO = SA.EMP_NO)
ORDER BY HE.EMP_NO ASC

-- 더 간단한 풀이
SELECT 
    HE.EMP_NO, 
    HE.EMP_NAME, 
    CASE 
        WHEN AVG(HG.SCORE) >= 96 THEN 'S'
        WHEN AVG(HG.SCORE) >= 90 THEN 'A'
        WHEN AVG(HG.SCORE) >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE 
        WHEN AVG(HG.SCORE) >= 96 THEN HE.SAL * 0.2
        WHEN AVG(HG.SCORE) >= 90 THEN HE.SAL * 0.15
        WHEN AVG(HG.SCORE) >= 80 THEN HE.SAL * 0.1
        ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES HE
JOIN HR_GRADE HG ON HE.EMP_NO = HG.EMP_NO -- 성적이 있는 사원만 조회한다면 JOIN
GROUP BY HE.EMP_NO -- 사원별로 그룹화
ORDER BY HE.EMP_NO;

-- 등급표를 미리 만들어서 문제 풆이
WITH GRADE_RULES AS (
    -- 등급 기준표를 정의
    SELECT 96 AS MIN_SCORE, 'S' AS GRADE, 0.2 AS RATE UNION ALL
    SELECT 90, 'A', 0.15 UNION ALL
    SELECT 80, 'B', 0.1 UNION ALL
    SELECT 0, 'C', 0
)

SELECT 
    E.EMP_NO, E.EMP_NAME, 
    R.GRADE, 
    (E.SAL * R.RATE) AS BONUS
FROM (
    -- 사원별 평균 점수를 먼저 계산
    SELECT EMP_NO, AVG(SCORE) AS AVG_SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
) AS S
JOIN HR_EMPLOYEES E ON S.EMP_NO = E.EMP_NO
JOIN GRADE_RULES R ON S.AVG_SCORE >= R.MIN_SCORE
-- 여러 조건 중 가장 높은 등급 하나만 매칭되도록 처리
WHERE R.MIN_SCORE = (
    SELECT MAX(MIN_SCORE) 
    FROM GRADE_RULES 
    WHERE S.AVG_SCORE >= MIN_SCORE
)
ORDER BY E.EMP_NO;