SELECT CC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CC JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CH ON CC.CAR_ID = CH.CAR_ID
WHERE CAR_TYPE = '세단' AND START_DATE BETWEEN '2022-10-01' AND '2022-10-31'
GROUP BY CC.CAR_ID
ORDER BY CC.CAR_ID DESC
