WITH T AS (
    SELECT HISTORY_ID, CC.CAR_TYPE, 
    DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) AS RENT,
    CASE
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
        ELSE NULL
    END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CH JOIN CAR_RENTAL_COMPANY_CAR CC 
    ON CH.CAR_ID = CC.CAR_ID
    WHERE CC.CAR_TYPE = '트럭')

SELECT 
    HISTORY_ID, 
    FLOOR(RENT * ((100 - IFNULL(DISCOUNT_RATE, 0)) / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN CP RIGHT JOIN T 
    ON CP.DURATION_TYPE = T.DURATION_TYPE 
    AND CP.CAR_TYPE = T.CAR_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC