-- Table: ECOLI_DATA
-- Att: ID, PARENT_ID, SIZE_OF_COLONY, DIFFERENTIATION_DATE, GENOTYPE
-- 1번이나 3번 형질 : 0101(2) = 5, 2번 형질 : 0010(2) = 2

SELECT COUNT(*) AS 'COUNT'
FROM ECOLI_DATA
WHERE GENOTYPE & 5 != 0 AND GENOTYPE & 2 = 0