-- 2021년에 가입한 유저들의 ID
WITH USER_JOIN AS (SELECT USER_ID
              FROM USER_INFO
              WHERE JOINED LIKE '2021%')

SELECT YEAR(SALES_DATE) AS YAER, 
MONTH(SALES_DATE) AS MONTH, 
COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS, 
ROUND(COUNT(DISTINCT OS.USER_ID) / (SELECT COUNT(USER_ID)
                              FROM USER_INFO
                              WHERE JOINED LIKE '2021%'), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE OS JOIN USER_JOIN UJ ON OS.USER_ID = UJ.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE)