-- PATIENT
-- PT_NO, PT_NAME, GEND_CD, AGE, TLNO

-- 1.JOIN
SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN ICECREAM_INFO I ON F.FLAVOR = I.FLAVOR
WHERE F.TOTAL_ORDER > 3000 
  AND I.INGREDIENT_TYPE = 'fruit_based'
ORDER BY F.TOTAL_ORDER DESC;

-- 2.SUB_QUREY(IN)
SELECT FLAVOR
FROM FIRST_HALF
WHERE TOTAL_ORDER > 3000
  AND FLAVOR IN (
      SELECT FLAVOR 
      FROM ICECREAM_INFO 
      WHERE INGREDIENT_TYPE = 'fruit_based'
  )
ORDER BY TOTAL_ORDER DESC;

-- 3.EXISTS
SELECT F.FLAVOR
FROM FIRST_HALF F
WHERE F.TOTAL_ORDER > 3000
  AND EXISTS (
      SELECT 1 
      FROM ICECREAM_INFO I 
      WHERE I.FLAVOR = F.FLAVOR 
        AND I.INGREDIENT_TYPE = 'fruit_based'
  )
ORDER BY F.TOTAL_ORDER DESC;