-- SUBQUERY
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (SELECT FOOD_TYPE, MAX(FAVORITES)
                                FROM REST_INFO
                                GROUP BY FOOD_TYPE)
ORDER BY FOOD_TYPE DESC

-- RANK
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (SELECT *, RANK() OVER (PARTITION BY FOOD_TYPE 
                             ORDER BY FAVORITES DESC) AS RK
     FROM REST_INFO) AS T
WHERE RK = 1
ORDER BY FOOD_TYPE DESC