-- Table: ECOLI_DATA
-- Att: ID, PARENT_ID, SIZE_OF_COLONY, DIFFERENTIATION_DATE, GENOTYPE
-- 부모의 형질을 모두 보유한 대장균을 추출

SELECT CE.ID, CE.GENOTYPE, PE.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA CE LEFT JOIN ECOLI_DATA PE ON CE.PARENT_ID = PE.ID
WHERE CE.GENOTYPE & PE.GENOTYPE = PE.GENOTYPE -- 부모의 형질을 "모두" 가진 자식만 추출
ORDER BY CE.ID