SELECT YEAR(OS.SALES_DATE) AS YAER,
    MONTH(OS.SALES_DATE) AS MONTH,
    UI.GENDER AS GENDER,
    COUNT(DISTINCT UI.USER_ID) AS USERS      
FROM USER_INFO UI 
    JOIN ONLINE_SALE OS 
    ON UI.USER_ID = OS.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE), GENDER
ORDER BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE), GENDER