-- FIRST_HALF
-- SHIPMENT_ID, FLAVOR, TOTAL_ORDER
-- ICECREAM_INFO
-- FLAVOR, INGREDIENT_TYPE

SELECT II.INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF FH JOIN ICECREAM_INFO II ON FH.FLAVOR = II.FLAVOR
GROUP BY II.INGREDIENT_TYPE