WITH DISCOUNT AS (SELECT CAR_TYPE, DISCOUNT_RATE
                  FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                  WHERE DURATION_TYPE = '30일 이상'),
AVAIL AS (SELECT *
         FROM CAR_RENTAL_COMPANY_CAR
         WHERE CAR_TYPE IN ('세단', 'SUV')
         AND CAR_ID NOT IN (SELECT CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'))

SELECT A.CAR_ID, A.CAR_TYPE, FLOOR((DAILY_FEE * 30) * (100-DISCOUNT_RATE) / 100) AS FEE
FROM AVAIL A JOIN DISCOUNT D ON A.CAR_TYPE = D.CAR_TYPE
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC