-- Table : FISH_INFO
-- Att : ID, FISH_TYPE, LENGTH, TIME

-- Table : FISH_NAME_INFO
-- Att : FISH_TYPE, FISH_NAME

SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO
WHERE FISH_TYPE IN (SELECT FISH_TYPE
                   FROM FISH_NAME_INFO
                   WHERE FISH_NAME IN ('BASS', 'SNAPPER'))