SELECT UU.USER_ID, UU.NICKNAME, TT.TOTAL_SALES
FROM USED_GOODS_USER UU 
JOIN (SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000) AS TT 
ON UU.USER_ID = TT.WRITER_ID
ORDER BY TOTAL_SALES ASC