WITH M_RK AS (SELECT MEMBER_ID, 
RANK() OVER(ORDER BY COUNT(*) DESC) AS RK
FROM REST_REVIEW
GROUP BY MEMBER_ID)

SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d')
FROM M_RK M JOIN MEMBER_PROFILE MP ON M.MEMBER_ID = MP.MEMBER_ID
JOIN REST_REVIEW RR ON M.MEMBER_ID = RR.MEMBER_ID
WHERE M.RK = 1
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT