-- MEMBER_PROFILE
-- MEMBER_ID, MEMBER_NAME, TLNO, GENDER, DATE_OF_BIRTH
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d')
FROM MEMBER_PROFILE
WHERE GENDER = 'W' 
    and DATE_OF_BIRTH LIKE '%-03-%' 
    and TLNO IS NOT NULL