-- Table: ECOLI_DATA
-- Att: ID, PARENT_ID, SIZE_OF_COLONY, DIFFERENTIATION_DATE, GENOTYPE
-- 부모의 형질을 모두 보유한 대장균을 추출

SELECT ID, 
       CASE 
           WHEN QUARTILE = 1 THEN 'CRITICAL'
           WHEN QUARTILE = 2 THEN 'HIGH'
           WHEN QUARTILE = 3 THEN 'MEDIUM'
           ELSE 'LOW'
       END AS COLONY_NAME
FROM (
    SELECT ID, 
           NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS QUARTILE -- NTILE 함수를 사용해서, 4등분
    FROM ECOLI_DATA
) AS SUBQUERY
ORDER BY ID ASC;