-- 조회수가 가장 높은 중고거래 게시물 찾기
SET @TOPVIEW = (SELECT BOARD_ID
FROM USED_GOODS_BOARD
ORDER BY VIEWS DESC
LIMIT 1);

SELECT CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE
WHERE BOARD_ID = @TOPVIEW
ORDER BY FILE_ID DESC;
