-- FOOD_PRODUCT
-- PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE

SELECT CATEGORY, 
    PRICE AS MAX_PRICE,
    PRODUCT_NAME
FROM (
    SELECT *, 
    RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RK
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    ) AS T
WHERE RK = 1
ORDER BY MAX_PRICE DESC