WITH TOTAL_SALES AS (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALE
                    FROM OFFLINE_SALE
                    GROUP BY PRODUCT_ID)

SELECT P.PRODUCT_CODE, PRICE * SALE AS SALES
FROM PRODUCT P JOIN TOTAL_SALES TS ON P.PRODUCT_ID = TS.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE