# 1.Table: BOOK
# Att: BOOK_ID, CATEGORY, AUTHOR_ID, PRICE, PUBLISHED_DATE
# 2.Table: AUTHOR
# Att: AUTHOR_ID, AUTHOR_NAME
# 3.Table: BOOK_SALES
# Att: BOOK_ID, SALES_DATE, SALES

SELECT 
    A.AUTHOR_ID, 
    A.AUTHOR_NAME, 
    B.CATEGORY, 
    SUM(B.PRICE * BS.SALES) AS TOTAL_SALES -- 총 합
FROM BOOK_SALES BS
JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE BS.SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_ID, B.CATEGORY -- 저자 ID별, 카테고리 별 그룹화
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;