-- ECOLI_DATA
-- ID, PARENT_ID, SIZE_OF_COLONY, DIFFERENTIATION_DATE, GENOTYPE

SELECT ID, 
CASE
    WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
    WHEN SIZE_OF_COLONY > 1000 THEN 'HIGH'
    ELSE 'MEDIUM'
END AS SIZE
FROM ECOLI_DATA
ORDER BY ID ASC