SELECT B.CATEGORY, SUM(BT.TOTAL_SALES)
FROM BOOK B JOIN (SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
                  FROM BOOK_SALES
                  WHERE SALES_DATE LIKE '2022-01%'
                  GROUP BY BOOK_ID) AS BT ON B.BOOK_ID = BT.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC