-- Table: ECOLI_DATA
-- Att: ID, PARENT_ID, SIZE_OF_COLONY, DIFFERENTIATION_DATE, GENOTYPE

-- 서브 쿼리
SELECT ID, 
       CASE 
           WHEN QUARTILE = 1 THEN 'CRITICAL'
           WHEN QUARTILE = 2 THEN 'HIGH'
           WHEN QUARTILE = 3 THEN 'MEDIUM'
           ELSE 'LOW'
       END AS COLONY_NAME
FROM (
    SELECT ID, 
           NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS QUARTILE -- NTILE 함수를 사용해서, 4등분
    FROM ECOLI_DATA
) AS SUBQUERY
ORDER BY ID ASC;

-- JOIN
SELECT C.ID
FROM ECOLI_DATA C              -- C: 자식 (3세대)
JOIN ECOLI_DATA P ON C.PARENT_ID = P.ID   -- P: 부모 (2세대)
JOIN ECOLI_DATA G ON P.PARENT_ID = G.ID   -- G: 할아버지 (1세대)
WHERE G.PARENT_ID IS NULL                 -- 할아버지가 1세대(ROOT)인 경우
ORDER BY C.ID ASC;

-- WITH, 임시 테이블 생성
WITH FIRST_GEN AS (
    SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IS NULL
),
SECOND_GEN AS (
    SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IN (SELECT ID FROM FIRST_GEN)
)
SELECT ID 
FROM ECOLI_DATA 
WHERE PARENT_ID IN (SELECT ID FROM SECOND_GEN)
ORDER BY ID;

-- 재귀 쿼리
WITH RECURSIVE ECOLI_TREE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, ET.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN ECOLI_TREE ET ON E.PARENT_ID = ET.ID
)
SELECT ID FROM ECOLI_TREE WHERE GENERATION = 3
ORDER BY ID;