-- Table: ECOLI_DATA
-- Att: ID, PARENT_ID, SIZE_OF_COLONY, DIFFERENTIATION_DATE, GENOTYPE

WITH RECURSIVE ECOLI_GENERATION AS (
    -- 1세대 대장균
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    -- N세대 대장균
    SELECT E.ID, E.PARENT_ID, EG.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN ECOLI_GENERATION EG ON E.PARENT_ID = EG.ID
)
SELECT COUNT(*) AS COUNT, GENERATION
FROM ECOLI_GENERATION
-- 누군가의 부모 ID에 포함되지 않는 경우만 찾기
WHERE ID NOT IN (SELECT PARENT_ID 
                 FROM ECOLI_DATA 
                 WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION -- 세대 별 이므로, 세대별로 그룹 화
ORDER BY GENERATION ASC;